name: Linux Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Add permissions
        run: |
          chmod +x libMujina/InjectableJar/ignore_File2Hex
          chmod +x build.sh
      
      - name: Build
        run: ./build.sh
      
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "linux"
          prerelease: true
          title: "Linux Nightly Build"
          files: |
            *.so
